#!/usr/bin/env bash
#todo make a workflow on GitHub
echo "//git statistics. this file is auto-generated, please do not edit it. it's generated by the update_git_statistics.sh." > "src/git_stats.h"
echo "#ifndef GIT_STATS_H" >> "src/git_stats.h"
echo "#define GIT_STATS_H" >> "src/git_stats.h"
echo "namespace git_stats {" >> "src/git_stats.h"
echo -n "    const char * contributor_loc = " >> "src/git_stats.h"
git ls-tree -r HEAD \
| sed -Ee 's/^.{53}//' \
| while read filename; do file "$filename"; done \
| grep -E ': .*text' \
| sed -E -e 's/: .*//' \
| while read filename; do git blame --line-porcelain "$filename"; done \
| sed -n 's/^author //p' \
| sort \
| uniq -c \
| sort -rn \
| awk '{printf "\n    \"%s\\n\"", $0}'\
>>"src/git_stats.h"
echo ";" >> "src/git_stats.h"

echo -n "    float total_hours = " >> "src/git_stats.h"
git log --all | grep -oE "t=[0-9]+\\.?[0-9]*" | grep -oE "[0-9]+\\.?[0-9]*" | awk '{ SUM += $1} END { printf "%f;\n", SUM }' >> "src/git_stats.h"

echo -n "    unsigned int commit_count = " >> "src/git_stats.h"
git log --oneline | wc -l | awk '{ printf "%d;", $0}' >> "src/git_stats.h"

echo -n -e "\n    const char* lastCommitHash = " >> "src/git_stats.h"
git log HEAD -n 1 --format=%H | awk '{ printf "\"%s\";\n", $0}' >> "src/git_stats.h"

echo "}" >> "src/git_stats.h"
echo "#endif //GIT_STATS_H" >> "src/git_stats.h"
