#!/usr/bin/env bash
echo "//git statistics. this file is auto-generated, please do not edit it. it's generated by the update_git_statistics.sh." > "src/constant_data/git_stats.cpp"
echo '#include "git_stats.h"' >> "src/constant_data/git_stats.cpp"

#todo exclude src/lib
echo -n "const char * git_stats::contributorLoc = " >> "src/constant_data/git_stats.cpp"
git ls-tree -r HEAD \
| sed -Ee 's/^.{53}//' \
| while read filename; do file "$filename"; done \
| grep -E ': .*text' \
| sed -E -e 's/: .*//' \
| while read filename; do git blame --line-porcelain "$filename"; done \
| sed -n 's/^author //p' \
| sort \
| uniq -c \
| sort -rn \
| awk '{printf "\n    \"%s\\n\"", $0}'\
>>"src/constant_data/git_stats.cpp"
echo ";" >> "src/constant_data/git_stats.cpp"

echo -n "float git_stats::totalHours = " >> "src/constant_data/git_stats.cpp"
git log --no-merges --all | grep -oE "t=[0-9]+\\.?[0-9]*" | grep -oE "[0-9]+\\.?[0-9]*" | awk '{ SUM += $1} END { printf "%f;\n", SUM }' >> "src/constant_data/git_stats.cpp"

echo -n "unsigned int git_stats::commitCount = " >> "src/constant_data/git_stats.cpp"
git log --oneline | wc -l | awk '{ printf "%d;", $0}' >> "src/constant_data/git_stats.cpp"

echo -n -e "\nconst char* git_stats::lastCommitHash = " >> "src/constant_data/git_stats.cpp"
git log HEAD -n 1 --format=%H | awk '{ printf "\"%s\";\n", $0}' >> "src/constant_data/git_stats.cpp"