//git statistics. this file is auto-generated, please do not edit it. it's generated by the update_git_statistics.sh.
#ifndef GIT_STATS_H
#define GIT_STATS_H
class git_stats {
public:
    static const char * contributorLoc;
    static float totalHours;
    static unsigned int commitCount;
    static const char* lastCommitHash;
};
#endif //GIT_STATS_H
