//this file is automatically generated by scripts/resources_to_code.py, editing it is a bad idea
#include <array>
#include <cstdint>
namespace bricksim::resources {
    namespace fonts {
        extern const std::array<uint8_t, 171272> Roboto_Regular_ttf;
        extern const std::array<uint8_t, 86908> RobotoMono_Regular_ttf;
        extern const std::array<uint8_t, 394628> fa_solid_900_ttf;
    }
    namespace licenses {
        extern const std::array<uint8_t, 11323> Apache2_txt;
        extern const std::array<uint8_t, 35128> GPLv3_txt;
        extern const std::array<uint8_t, 1068> MIT_txt;
        extern const std::array<uint8_t, 1321> bsd2clause_txt;
        extern const std::array<uint8_t, 1519> bsd3clause_txt;
        extern const std::array<uint8_t, 855> zlib_txt;
    }
    namespace logos {
        extern const std::array<uint8_t, 91911> logo_svg;
        extern const std::array<uint8_t, 67248> logo_fit_nobg_png;
        extern const std::array<uint8_t, 79933> logo_icon_icns;
        extern const std::array<uint8_t, 21573> logo_icon_ico;
        extern const std::array<uint8_t, 14020> logo_icon_png;
        extern const std::array<uint8_t, 3192> logo_icon_48x48_png;
    }
    namespace shaders {
        extern const std::array<uint8_t, 105> line_shader_fsh;
        extern const std::array<uint8_t, 688> line_shader_vsh;
        extern const std::array<uint8_t, 1020> optional_line_shader_gsh;
        extern const std::array<uint8_t, 721> optional_line_shader_vsh;
        extern const std::array<uint8_t, 187> overlay_shader_vsh;
        extern const std::array<uint8_t, 105> simple_color_forwarding_shader_fsh;
        extern const std::array<uint8_t, 337> textured_triangle_selection_shader_vsh;
        extern const std::array<uint8_t, 167> textured_triangle_shader_fsh;
        extern const std::array<uint8_t, 388> textured_triangle_shader_vsh;
        extern const std::array<uint8_t, 550> triangle_selection_shader_vsh;
        extern const std::array<uint8_t, 967> triangle_shader_fsh;
        extern const std::array<uint8_t, 870> triangle_shader_vsh;
    }
    extern const std::array<uint8_t, 16734> icons_png;
    extern const std::array<uint8_t, 55379> orientation_cube_png;
}
