//this file is automatically generated by scripts/resources_to_code.py, editing it is a bad idea
#include <array>
#include <cstdint>
namespace bricksim::resources {
    namespace fonts {
        extern const std::array<uint8_t, 171272> Roboto_Regular_ttf;
        extern const std::array<uint8_t, 86908> RobotoMono_Regular_ttf;
        extern const std::array<uint8_t, 394628> fa_solid_900_ttf;
    }
    namespace icons {
        namespace _16x16 {
            extern const std::array<uint8_t, 171> brick_1_side_png;
            extern const std::array<uint8_t, 304> brick_1x1_top_png;
            extern const std::array<uint8_t, 179> brick_2_side_png;
            extern const std::array<uint8_t, 310> brick_2x2_top_png;
            extern const std::array<uint8_t, 249> plate_1_half_top_png;
            extern const std::array<uint8_t, 167> plate_1_side_png;
            extern const std::array<uint8_t, 180> plate_2_side_png;
            extern const std::array<uint8_t, 207> select_png;
            extern const std::array<uint8_t, 409> select_connected_png;
            extern const std::array<uint8_t, 334> select_strongly_connected_png;
        }
        namespace _36x36 {
            extern const std::array<uint8_t, 197> brick_1_side_png;
            extern const std::array<uint8_t, 597> brick_1x1_top_png;
            extern const std::array<uint8_t, 197> brick_2_side_png;
            extern const std::array<uint8_t, 741> brick_2x2_top_png;
            extern const std::array<uint8_t, 447> plate_1_half_top_png;
            extern const std::array<uint8_t, 201> plate_1_side_png;
            extern const std::array<uint8_t, 203> plate_2_side_png;
            extern const std::array<uint8_t, 435> select_png;
            extern const std::array<uint8_t, 762> select_connected_png;
            extern const std::array<uint8_t, 607> select_strongly_connected_png;
        }
        namespace _48x48 {
            extern const std::array<uint8_t, 201> brick_1_side_png;
            extern const std::array<uint8_t, 754> brick_1x1_top_png;
            extern const std::array<uint8_t, 206> brick_2_side_png;
            extern const std::array<uint8_t, 941> brick_2x2_top_png;
            extern const std::array<uint8_t, 562> plate_1_half_top_png;
            extern const std::array<uint8_t, 186> plate_1_side_png;
            extern const std::array<uint8_t, 206> plate_2_side_png;
            extern const std::array<uint8_t, 525> select_png;
            extern const std::array<uint8_t, 1057> select_connected_png;
            extern const std::array<uint8_t, 739> select_strongly_connected_png;
        }
    }
    namespace licenses {
        extern const std::array<uint8_t, 11323> Apache2_txt;
        extern const std::array<uint8_t, 35128> GPLv3_txt;
        extern const std::array<uint8_t, 1068> MIT_txt;
        extern const std::array<uint8_t, 1321> bsd2clause_txt;
        extern const std::array<uint8_t, 1519> bsd3clause_txt;
        extern const std::array<uint8_t, 855> zlib_txt;
    }
    namespace logos {
        extern const std::array<uint8_t, 67248> logo_fit_nobg_png;
        extern const std::array<uint8_t, 79933> logo_icon_icns;
        extern const std::array<uint8_t, 21573> logo_icon_ico;
        extern const std::array<uint8_t, 14020> logo_icon_png;
        extern const std::array<uint8_t, 3192> logo_icon_48x48_png;
    }
    namespace shaders {
        extern const std::array<uint8_t, 105> line_shader_fsh;
        extern const std::array<uint8_t, 688> line_shader_vsh;
        extern const std::array<uint8_t, 1020> optional_line_shader_gsh;
        extern const std::array<uint8_t, 721> optional_line_shader_vsh;
        extern const std::array<uint8_t, 187> overlay_shader_vsh;
        extern const std::array<uint8_t, 105> simple_color_forwarding_shader_fsh;
        extern const std::array<uint8_t, 337> textured_triangle_selection_shader_vsh;
        extern const std::array<uint8_t, 167> textured_triangle_shader_fsh;
        extern const std::array<uint8_t, 388> textured_triangle_shader_vsh;
        extern const std::array<uint8_t, 550> triangle_selection_shader_vsh;
        extern const std::array<uint8_t, 967> triangle_shader_fsh;
        extern const std::array<uint8_t, 870> triangle_shader_vsh;
    }
    extern const std::array<uint8_t, 55379> orientation_cube_png;
}
