//this file is automatically generated by scripts/resources_to_code.py, editing it is a bad idea
#include <array>
#include <cstdint>
namespace bricksim::resources {
    namespace fonts {
        extern const std::array<uint8_t, 171272> Roboto_Regular_ttf;
        extern const std::array<uint8_t, 86908> RobotoMono_Regular_ttf;
        extern const std::array<uint8_t, 204528> fa_solid_900_ttf;
    }
    namespace licenses {
        extern const std::array<uint8_t, 11523> Apache2_txt;
        extern const std::array<uint8_t, 35801> GPLv3_txt;
        extern const std::array<uint8_t, 1088> MIT_txt;
        extern const std::array<uint8_t, 1345> bsd2clause_txt;
        extern const std::array<uint8_t, 1547> bsd3clause_txt;
        extern const std::array<uint8_t, 873> zlib_txt;
    }
    namespace logos {
        extern const std::array<uint8_t, 91911> logo_svg;
        extern const std::array<uint8_t, 67248> logo_fit_nobg_png;
        extern const std::array<uint8_t, 21573> logo_icon_ico;
        extern const std::array<uint8_t, 14020> logo_icon_png;
        extern const std::array<uint8_t, 3192> logo_icon_48x48_png;
    }
    extern const std::array<uint8_t, 55379> orientation_cube_png;
    namespace shaders {
        extern const std::array<uint8_t, 113> line_shader_fsh;
        extern const std::array<uint8_t, 711> line_shader_vsh;
        extern const std::array<uint8_t, 1046> optional_line_shader_gsh;
        extern const std::array<uint8_t, 746> optional_line_shader_vsh;
        extern const std::array<uint8_t, 197> overlay_shader_vsh;
        extern const std::array<uint8_t, 113> simple_color_forwarding_shader_fsh;
        extern const std::array<uint8_t, 351> textured_triangle_selection_shader_vsh;
        extern const std::array<uint8_t, 198> textured_triangle_shader_fsh;
        extern const std::array<uint8_t, 404> textured_triangle_shader_vsh;
        extern const std::array<uint8_t, 572> triangle_selection_shader_vsh;
        extern const std::array<uint8_t, 1007> triangle_shader_fsh;
        extern const std::array<uint8_t, 900> triangle_shader_vsh;
    }
}
