#ifndef BRICKSIM_RESOURCES_H
#define BRICKSIM_RESOURCES_H
    //do not edit this file, it is automatically generated!
    namespace resources {
    extern const unsigned char fonts_RobotoMono_Regular_ttf[];
    extern const unsigned int fonts_RobotoMono_Regular_ttf_len;
    extern const unsigned char fonts_Roboto_Regular_ttf[];
    extern const unsigned int fonts_Roboto_Regular_ttf_len;
    extern const unsigned char fonts_fa_solid_900_ttf[];
    extern const unsigned int fonts_fa_solid_900_ttf_len;
    extern const unsigned char orientation_cube_jpg[];
    extern const unsigned int orientation_cube_jpg_len;
}
#endif //BRICKSIM_RESOURCES_H
