name: CMake Windows Build
on:
  pull_request:
  workflow_dispatch:
  push:
    paths-ignore:
      - "docs/**"
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash.exe --login -eo pipefail "{0}"

    env:
      MSYSTEM: MINGW64

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Get info
      run: |
        echo $PWD
        echo "runner.workspace: \"${{runner.workspace}}\""

    - name: Setup workspace
      run: ./setup_workspace.sh

    - name: Build
      env:
        CC: /C/msys64/mingw64/bin/gcc.exe
        CXX: /C/msys64/mingw64/bin/g++.exe
      run: |
        cmake -G "MinGW Makefiles" . -DCMAKE_PREFIX_PATH=/C/mingw64
        cmake --build . --config Release

    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: BrickSimWindows
        # todo include README.md
        path: ${{runner.workspace}}/build/BrickSim
