name: CMake Linux Build
on:
  pull_request:
  push:
    paths-ignore:
      - "docs/**"
env:
  BUILD_TYPE: Release
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-20.04 # todo set this back to ubuntu-latest when ubuntu-latest is 20.04 or higher

    steps:
    - uses: actions/checkout@v2
    
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    
    - name: Setup Workspace
      run: ./setup_workspace.sh

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: cpp

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      env:
        CC: gcc-10
        CXX: g++-10

    - name: get infos
      run: |
        gcc --version
        whereis gcc
        echo "runner.workspace: \"${{runner.workspace}}\""

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

    - name: Create .deb using CPack
      run: |
        LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${{runner.workspace}}/build/lib
        echo "$LD_LIBRARY_PATH"
        sudo ldconfig
        cpack --config ${{runner.workspace}}/build/CPackConfig.cmake

    - name: Copy the .deb file
      run: cp -f ${{runner.workspace}}/BrickSim/_CPack_Packages/Linux/DEB/BrickSim.deb ${{runner.workspace}}/BrickSim/BrickSim.deb

    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: BrickSimLinux
        path: |
          ${{runner.workspace}}/BrickSim/BrickSim.deb
          ${{runner.workspace}}/BrickSim/README.md
