name: CMake Linux Build
on:
  pull_request:
  push:
    paths-ignore:
      - "docs/**"
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    
    - name: Setup Workspace
      run: ./setup_workspace.sh

    - name: Update Git Stats
      #The changes aren't committed but they should be included in the binary so it's done here too
      run: ./update_git_statistics.sh

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: cpp

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      env:
        CC: gcc-10
        CXX: g++-10

    - name: get infos
      run: |
        gcc --version
        whereis gcc

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE

    #todo- name: Perform CodeQL Analysis
    #todo  uses: github/codeql-action/analyze@v1

    #- name: add local libraries to $LD_LIBRARY_PATH

    #- name: Get info
    #  run: |
    #    whereis libGLEW.so.2.1
      #sudo find / -iname "libGLEW.so.*"

    - name: Create .deb using CPack
      run: |
        LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${{runner.workspace}}/build/lib
        cpack --config ${{runner.workspace}}/build/CPackConfig.cmake

    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: BrickSimLinux
        path: |
          ${{runner.workspace}}/_CPack_Packages/Linux/DEB/BrickSim.deb
          ${{runner.workspace}}/README.md
        #todo README.md is not in artifact -> find out why
