name: CMake Windows Build
on:
  pull_request:
  workflow_dispatch:
  push:
    paths-ignore:
      - "docs/**"
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
        #  todo look what happens if i copy the packages from setup_workspace here

    - name: Setup workspace
      run: ./setup_workspace.sh

    - name: Get info
      run: |
        echo $PWD
        echo "runner.workspace: \"${{runner.workspace}}\""
        git describe --tags
        ls -l /c/msys64/mingw64/bin | grep zip

    - name: Build
      env:
        CC: /C/msys64/mingw64/bin/gcc.exe
        CXX: /C/msys64/mingw64/bin/g++.exe
      run: |
        cmake -G "MinGW Makefiles" . -DCMAKE_PREFIX_PATH=/C/mingw64 -DGIT_COMMIT_HASH:STRING=$(./scripts/get_git_commit_hash.sh) -DGIT_COMMIT_COUNT:STRING=$(./scripts/get_git_commit_count.sh) -DTOTAL_HOURS:STRING=$(./scripts/get_git_total_hours.sh) -DGIT_VERSION_TAG:STRING=$(./scripts/get_git_tag.sh)
        cmake --build . --config Release

    - name: Try to find binary
      run: find ${{runner.workspace}} -name "*.exe"

    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: BrickSimWindows
        # todo include README.md
        path: ${{runner.workspace}}/build/BrickSim
