#!/usr/bin/env bash

declare -a files=(
  "fonts/RobotoMono-Regular.ttf"
  "fonts/Roboto-Regular.ttf"
  "fonts/fa-solid-900.ttf"
  "orientation_cube.jpg"
  "logo_fit.png"
  "logo_fit_nobg.png"
  "logo_square.png"
  "logo_square_nobg.png"
  "logo_fit_highres.png"
  "logo_icon.png"
)

if [ ! -d "src" ]; then
  echo "please change the working directory to the repository root."
  exit 1
fi

echo -e "//do not edit this file, it is automatically generated!\nnamespace resources {\n" >"src/constant_data/resources.cpp"

cd resources || exit 1
for f in "${files[@]}"; do
  xxd -i -c 100000 "$f" >>../src/constant_data/resources.cpp
done
cd ..

sed -i -e "s/unsigned /extern const unsigned /g" src/constant_data/resources.cpp
cp src/constant_data/resources.cpp src/constant_data/resources.h
grep -v "\\s0x..," src/constant_data/resources.h >tmp.txt
mv tmp.txt src/constant_data/resources.h
sed -i -e "s/};//g" src/constant_data/resources.h
sed -i -e "s/ = .*$/;/g" src/constant_data/resources.h

echo -e "#ifndef BRICKSIM_RESOURCES_H\n#define BRICKSIM_RESOURCES_H\n$(awk '{ print "    " $0 }' src/constant_data/resources.h | sed '/^[[:space:]]*$/d')\n}\n#endif //BRICKSIM_RESOURCES_H" >src/constant_data/resources.h

echo -e "\n}" >>src/constant_data/resources.cpp
