#!/usr/bin/env bash

declare -a files=("fonts/RobotoMono-Regular.ttf"
                "fonts/Roboto-Regular.ttf"
                "fonts/fa-solid-900.ttf"
                "orientation_cube.jpg"
                )

if [ ! -d "src" ]; then
    echo "please change the working directory to the repository root."
    exit 1
fi

echo -e "//do not edit this file, it is automatically generated!\nnamespace resources {\n" > "src/resources.cpp"

cd resources || exit 1
for f in "${files[@]}"
do
  xxd -i -c 100000 "$f" >> ../src/resources.cpp
done
cd ..

sed -i -e "s/unsigned /extern const unsigned /g" src/resources.cpp
cp src/resources.cpp src/resources.h
grep -v "\\s0x..," src/resources.h > tmp.txt
mv tmp.txt src/resources.h
sed -i -e "s/};//g" src/resources.h
sed -i -e "s/ = .*$/;/g" src/resources.h

echo -e "#ifndef BRICKSIM_RESOURCES_H\n#define BRICKSIM_RESOURCES_H\n$(awk '{ print "    " $0 }' src/resources.h | sed '/^[[:space:]]*$/d')\n}\n#endif //BRICKSIM_RESOURCES_H" > src/resources.h

echo -e "\n}" >> src/resources.cpp