name: Update Git Statistic
on:
  workflow_dispatch:
  schedule:
    # At 03:43 on every sunday
    - cron: '43 3 * * SUN'
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'updated git_stats.h')"
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run update_git_statistics.sh
        run: ./update_git_statistics.sh
      - name: Commit the changes
        run: |
          echo "changes detected"
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Actions Bot"
          git add src/constant_data/git_stats.cpp
          git commit -m "GitHub Actions: updated git_stats.h"
          git push
