# This is a basic workflow to help you get started with Actions

name: Update Git Statistic

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Runs a single command using the runners shell
      - name: Run update_git_statistics.sh
        run: ./update_git_statistics.sh

      # Runs a set of commands using the runners shell
      - name: Commit the changes
        run: |
          git config --global user.name "GitHub Actions bot"
          git add src/git_stats.h
          git commit -m "GitHub Actions: updated git_stats.h"
          git push
